"""Standalone demo of the BRH constraints pipeline (no API key, no agentdojo).

Runs the full HTTP flow on a canned plan with a scripted annotator:

    plan → skeleton (AST) → annotation (LLM, validated) → plan_constraints.json
                                                        → branch_state.json (fail-closed)
         → runtime hook simulation (root activation + branch transitions)
                                                        → branch_state.json (resolved)

The runtime part drives `cobra.brh.hook` with the exact same calls the
interpreter's `_eval_if` makes, using a fake namespace in place of the
CaMeL one (the hook is duck-typed precisely so this works without the
interpreter's dependency chain).

Usage:
    PYTHONPATH=src python3 -m cobra.brh.demo [out_dir]
"""

import dataclasses
import json
import sys
from pathlib import Path

from cobra.brh import hook
from cobra.brh.skeleton import extract_skeleton
from cobra.brh.writer import BRHConfig, generate_plan_constraints

PLAN = '''\
```python
page = get_page_text("https://shop.example.com/usb-c-hub")
perceived_price = query_price(page)
print(perceived_price)
if perceived_price <= 50:
    product_id = find_product_id(page)
    order = place_order("payments.example.com", product_id, perceived_price)
    if order.confirmed:
        print("order ok")
    else:
        report_error(order)
else:
    print("too expensive")
```
'''

TASK = "Buy a USB-C hub from shop.example.com if the price is at most 50 GBP"

# Scripted annotator response standing in for the P-LLM. With a real model
# this is produced by PrivilegedLLM._pab_llm_call.
SCRIPTED_RESPONSE = """```json
{
  "branches": {
    "root": {
      "description": "initial observation of the product page",
      "trigger_var": null,
      "http_constraints": {"allowed_domains": ["shop.example.com"], "fields": []},
      "mcp_constraints": null
    },
    "if_L4_true": {
      "description": "purchase branch - price is within budget",
      "trigger_var": "perceived_price",
      "http_constraints": {
        "allowed_domains": ["shop.example.com", "payments.example.com"],
        "fields": [
          {"path": "amount", "op": "<=", "value": "trigger_value"},
          {"path": "currency", "op": "==", "value": "GBP"},
          {"path": "product_id", "op": "==", "value": "var:product_id"}
        ]
      },
      "mcp_constraints": null
    },
    "if_L4_false": {
      "description": "abort branch - price exceeds budget",
      "trigger_var": "perceived_price",
      "http_constraints": {"allowed_domains": [], "fields": []},
      "mcp_constraints": null
    },
    "if_L4_true.if_L7_true": {
      "description": "order confirmed",
      "trigger_var": "order",
      "http_constraints": {"allowed_domains": ["shop.example.com"], "fields": []},
      "mcp_constraints": null
    },
    "if_L4_true.if_L7_false": {
      "description": "order failed - report error, no retry",
      "trigger_var": "order",
      "http_constraints": {"allowed_domains": [], "fields": []},
      "mcp_constraints": null
    }
  }
}
```"""


# --- Minimal stand-ins for the interpreter objects the hook duck-types ---


class FakeCaMeLValue:
    def __init__(self, raw):
        self.raw = raw


class FakeNamespace:
    def __init__(self, variables):
        self.variables = variables

    def get(self, name):
        return self.variables.get(name)


@dataclasses.dataclass(frozen=True)
class FakeEvalArgs:
    brh_runtime: hook.BRHRuntime | None = None
    brh_branch_path: tuple = ()


def main() -> None:
    out_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("/tmp/brh")
    config = BRHConfig(out_dir=out_dir)

    print("=== 1. Plan generated by P-LLM ===")
    print(PLAN)

    skeleton = extract_skeleton(PLAN)
    print("=== 2. Deterministic AST skeleton ===")
    print(json.dumps(skeleton.summary(), indent=2))

    print("\n=== 3. Annotation + validation + write ===")
    constraints = generate_plan_constraints(
        llm_call=lambda system, user: SCRIPTED_RESPONSE,
        task=TASK,
        plan_markdown=PLAN,
        plan_id="demo_plan_0",
        config=config,
    )

    print(f"\n=== 4. {config.constraints_path} ===")
    print(config.constraints_path.read_text())
    print(f"=== 5. {config.state_path} (fail-closed until execution starts) ===")
    print(config.state_path.read_text())

    # --- Runtime hook simulation: what run_code + _eval_if do during execution ---
    runtime = hook.BRHRuntime(constraints=constraints, state_path=config.state_path)
    eval_args = hook.attach(FakeEvalArgs(), runtime)

    print("\n=== 6. Execution starts: root scope activated (run_code) ===")
    hook.activate_root(runtime)
    print(config.state_path.read_text())

    print("=== 7. Q-LLM perceives price 42.99 → `if perceived_price <= 50` is True (_eval_if L4) ===")
    namespace = FakeNamespace({"perceived_price": FakeCaMeLValue(42.99)})
    body_eval_args = hook.on_branch_entry(4, True, namespace, eval_args)
    print(config.state_path.read_text())

    print("=== 8. Order fails → nested `if order.confirmed` is False (_eval_if L7) ===")
    namespace.variables["order"] = FakeCaMeLValue(object())  # non-scalar → trigger_value null
    hook.on_branch_entry(7, False, namespace, body_eval_args)
    print(config.state_path.read_text())


if __name__ == "__main__":
    main()
